title:              Old Prints about Romania
email:              iulianl2000@gmail.com
description:        Old maps, prints and historical cartography of Romania and Eastern Europe.
author:             Iulian Lucaci
baseurl:            "/myblogsite"
url:                "https://transylvaniadigitalantiques.com"
lang:               en
locale:             en_US

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

seo:
  hide_comments: true

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

jekyll-archives:
  enabled:
    - year
    - month
  layouts:
    year: archive
    month: archive
  permalinks:
    year: /archives/:year/
    month: /archives/:year/:month/

# Tags
collections:
  posts:
    output: true
    permalink: /:categories/:title
    categories:
    - danube
    - transylvania
    - bukovina
    - banat
    - bessarabia
    - dobrogea
    - moldova
    - wallachia
    - europe

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Iulian Lucaci