title:              Old Prints about Romania
email:              iulianl2000@gmail.com
description:        A Blog Theme by Start Bootstrap
author:             Iulian Lucaci
baseurl:            "/myblogsite"
url:                "https://iulian-lucaci.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

#Tags
collections:
  posts:
    output: true
    permalink: /:categories/:title
    categories:
    - danube
    - transylvania

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Iulian Lucaci
